# Generated by Django 5.1.3 on 2025-04-18 22:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='sistema.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='sistema_ins_id_22d7cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=200, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiais', to='sistema.instituicao')),
            ],
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(blank=True, max_length=36, null=True)),
                ('acao', models.CharField(max_length=255)),
                ('tipo_recurso', models.CharField(max_length=255)),
                ('id_recurso', models.CharField(max_length=36)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['data_hora'], name='idx_log_auditoria_data_hora')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fcm', models.CharField(blank=True, max_length=255, null=True)),
                ('papel_usuario', models.CharField(choices=[('usuario', 'Usuário'), ('admin_departamento', 'Administrador de Departamento'), ('admin_instituicao', 'Administrador de Instituição'), ('admin_filial', 'Administrador de Filial')], default='usuario', max_length=20)),
                ('ultima_latitude', models.FloatField(blank=True, null=True)),
                ('ultima_longitude', models.FloatField(blank=True, null=True)),
                ('ultima_atualizacao_local', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='sistema.filial')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='sistema.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferida_por', to='sistema.categoria')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferida_por', to='sistema.instituicao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['id'], name='sistema_cat_id_81f997_idx'),
        ),
        migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['id'], name='sistema_fil_id_f9334f_idx'),
        ),
        migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['instituicao'], name='sistema_fil_institu_4980c5_idx'),
        ),
        migrations.AddIndex(
            model_name='filial',
            index=models.Index(fields=['bairro'], name='sistema_fil_bairro_f99aec_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['usuario'], name='sistema_per_usuario_1fc436_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['papel_usuario'], name='sistema_per_papel_u_7c3723_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['instituicao'], name='sistema_per_institu_a82c49_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['filial'], name='sistema_per_filial__fa81fa_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciausuario',
            index=models.Index(fields=['id'], name='sistema_pre_id_b94e49_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciausuario',
            index=models.Index(fields=['usuario'], name='idx_preferencia_usuario_id'),
        ),
        migrations.AddIndex(
            model_name='preferenciausuario',
            index=models.Index(fields=['instituicao'], name='sistema_pre_institu_a4810f_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciausuario',
            index=models.Index(fields=['categoria'], name='sistema_pre_categor_ef12b7_idx'),
        ),
    ]
