# Generated by Django 5.1.3 on 2025-04-18 22:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('setor', models.CharField(blank=True, max_length=50, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='sistema.filial')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('servico', models.CharField(max_length=50)),
                ('prefixo', models.CharField(max_length=10)),
                ('hora_abertura', models.TimeField()),
                ('hora_fechamento', models.TimeField(blank=True, null=True)),
                ('limite_diario', models.IntegerField()),
                ('tickets_ativos', models.IntegerField(default=0)),
                ('ticket_atual', models.IntegerField(default=0)),
                ('tempo_espera_medio', models.FloatField(blank=True, null=True)),
                ('ultimo_tempo_servico', models.FloatField(blank=True, null=True)),
                ('num_balcoes', models.IntegerField(default=1)),
                ('ultimo_balcao', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filas', to='sistema.categoria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='fila_online.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='EtiquetaServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etiqueta', models.CharField(max_length=50)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='fila_online.fila')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioFila',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('Segunda', 'Segunda-feira'), ('Terça', 'Terça-feira'), ('Quarta', 'Quarta-feira'), ('Quinta', 'Quinta-feira'), ('Sexta', 'Sexta-feira'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('hora_abertura', models.TimeField(blank=True, null=True)),
                ('hora_fechamento', models.TimeField(blank=True, null=True)),
                ('esta_fechado', models.BooleanField(default=False)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='fila_online.fila')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_ticket', models.IntegerField()),
                ('codigo_qr', models.CharField(max_length=50, unique=True)),
                ('prioridade', models.IntegerField(default=0)),
                ('e_fisico', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Atendido', 'Atendido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20)),
                ('emitido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('balcao', models.IntegerField(blank=True, null=True)),
                ('tempo_servico', models.FloatField(blank=True, null=True)),
                ('dados_recibo', models.TextField(blank=True, null=True)),
                ('troca_disponivel', models.BooleanField(default=False)),
                ('fila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='fila_online.fila')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['id'], name='fila_online_id_4e5954_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['filial'], name='fila_online_filial__a2c29f_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nome'], name='fila_online_nome_5589f7_idx'),
        ),
        migrations.AddIndex(
            model_name='fila',
            index=models.Index(fields=['id'], name='fila_online_id_7a2775_idx'),
        ),
        migrations.AddIndex(
            model_name='fila',
            index=models.Index(fields=['departamento'], name='fila_online_departa_45ace1_idx'),
        ),
        migrations.AddIndex(
            model_name='fila',
            index=models.Index(fields=['servico'], name='fila_online_servico_4954a1_idx'),
        ),
        migrations.AddIndex(
            model_name='fila',
            index=models.Index(fields=['categoria'], name='fila_online_categor_c0d7be_idx'),
        ),
        migrations.AddIndex(
            model_name='fila',
            index=models.Index(fields=['departamento', 'servico'], name='idx_fila_instituicao_servico'),
        ),
        migrations.AddIndex(
            model_name='etiquetaservico',
            index=models.Index(fields=['id'], name='fila_online_id_1e319c_idx'),
        ),
        migrations.AddIndex(
            model_name='etiquetaservico',
            index=models.Index(fields=['etiqueta'], name='fila_online_etiquet_bb333a_idx'),
        ),
        migrations.AddIndex(
            model_name='etiquetaservico',
            index=models.Index(fields=['fila'], name='fila_online_fila_id_bdabc8_idx'),
        ),
        migrations.AddIndex(
            model_name='horariofila',
            index=models.Index(fields=['fila'], name='idx_horario_fila_id'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['id'], name='fila_online_id_366465_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['fila'], name='fila_online_fila_id_dbb2c6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['usuario'], name='fila_online_usuario_a9d6a9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['codigo_qr'], name='fila_online_codigo__17fb1a_idx'),
        ),
    ]
